dist: bionic
language: csharp
mono: none
dotnet: 2.2.202
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - ./build.sh
before_deploy:
  - ./package.sh
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  file: 
    - "Retina/retina-win-x64.tar.gz"
    - "Retina/retina-linux-x64.tar.gz"
  on:
    tags: true
cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
